// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Field { id: number, name: string, xpath: string, try_follow: boolean, group_to: string | null, page_id: number, created_at: string, updated_at: string, }