// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKind } from "./JobKind";
import type { JobStatus } from "./JobStatus";

export interface Job { id: number, kind: JobKind, message: string, status: JobStatus, fail_message: string | null, fail_attempts: number, created_at: string, updated_at: string, started_at: string | null, successed_at: string | null, }