// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Field } from "./Field";
import type { Page } from "./Page";

export interface PageResponse { page: Page, fields: Array<Field>, }