// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Page { id: number, name: string, url: string | null, url_pattern: string, site_id: number, created_at: string, updated_at: string, }