// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReaderResponse } from "./ReaderResponse";

export interface ReadersResponse { readers: Array<ReaderResponse>, }