// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reader } from "./Reader";
import type { ReaderBlock } from "./ReaderBlock";

export interface ReaderResponse { reader: Reader, blocks: Array<ReaderBlock>, }