[package]
name = "scrapee-ui"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"
rust-version = "1.57"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.1", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tauri = { version = "1.1", features = ["api-all"] }

tokio = { version = "1.1", features = ["full"] }
env_logger = "0.9"
log = { version = "0.4", features = ["max_level_debug", "release_max_level_info"] }

[dependencies.scrapee-api]
path = "../../scrapee-api"

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
