[tasks.remove-db]
command = "rm"
args = ["a.db", "a.db-shm", "a.db-wal"]
ignore_errors = true

[tasks.create-db]
command = "sqlx"
args = ["database", "create", "--database-url", "sqlite:a.db"]

[tasks.migrate-db]
command = "sqlx"
args = ["migrate", "run", "--database-url", "sqlite:a.db"]

[tasks.generate-entities]
command = "sea-orm-cli"
args = ["generate", "entity", "-u", "sqlite:a.db", "--with-serde", "both", "-o", "sea_orm_generated"]

[tasks.reset-db]
dependencies = ["remove-db", "create-db", "migrate-db", "generate-entities"]

[tasks.rm-ts-bindings]
command = "rm"
args = ["-rf", "./bindings"]

[tasks.ts-rs]
command = "cargo"
args = ["test"]

[tasks.combine-ts]
# https://stackoverflow.com/questions/965053/extract-filename-and-extension-in-bash
script = '''
cd bindings

for f in *.ts ;
  do if [[ $f != "index.ts" ]] ;
    then echo "export * from './${f%%.*}';" ;
  fi ;
done > index.ts
'''